apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-server-block
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
{{- if .Values.serverBlock }}
  nginx.conf: |-
{{ .Values.serverBlock | indent 4 }}
{{- end }}
