apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-static-site
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
{{- if .Values.staticSite }}
  index.html: |-
{{ .Values.staticSite | indent 4 }}
{{- end }}
