annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.21.0
description: Chart for the nginx server
keywords:
- nginx
maintainers:
- email: shekhawatyuvraj1998@gmail.com
  name: Nginx
name: nginx
sources:
- https://hub.docker.com/_/nginx
- http://www.nginx.org
version: 9.3.4
